### ISSUE TITLE
Setting up projects

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#11]
Based on the reading, what would you consider are the two most important things to consider when setting up a bioinformatics project?

**Comment by Ellior2** [comment]
1) Make sure to document your process always (methods, workflows, the origin of all your data, when you downloaded data, data version, how you downloaded data, and versions of software you ran).

2) Don't trust your tools or data! There may be "silent" errors in your output.

**Comment by mfisher5** [comment]
1. Document everything in plain-text README files (even the versions of the software you are running, and the default values) -- and when you do, make sure the documentation is easy to find, read, and understand!
2. Keep your files and directories well-organized and name then consistently, using a system that can be extended without being confusing (ie. specific subanalysis type + date, instead of general names like "reanalyzed data")

**Comment by yaaminiv** [comment]
- Each project should have its own specific directory. A directory should include any data, analyses and scripts used. Additionally, everything in this directory should be well-documented. Methods, workflows, data origin, download dates and versions must be included in a way that's easy to access and understand.
- Always organize your directory in a way that you — or someone else — can understand it in 10+ years! This includes naming files using a consistent mechanism, like "2016-10-05-oystersamplingdata" instead of "datarevisedversion3."

**Comment by jldimond** [comment]
- Treat data as read only, and put analysis output in separate directory with well documented workflows.
- Strive to make everything you do as reproducible as possible for not just you but for anyone.

**Comment by nclowell** [comment]
1. Never trust your data or your tools! So get in the habit of testing assumptions, checking for silent errors, etc.
2. Consistent and informative naming of files and directories, so that you don't accidentally call the wrong file/directory

**Comment by aspanjer** [comment]
1. Your data organization structure, so that files are well organized and consistently named enabling better collaboration, analysis, and reproducibility. 
2. That you document your analysis steps in a format that is easy to share and allows others to reproduce your work (a plain text format with markdown for formatting accomplishes just this, and is easy to share).

**Comment by laurahspencer** [comment]
1) Appropriate/thoughtful organization of files and a systematic file naming convention that will allow easy/foolproof access in BASH  
 2) Setting yourself up for full documentation of every step including: README files, methods & workflow, software versions, default software values, source/date of data received.  
**Question: do people include a list of command definitions in their project documentation?**

**Comment by mmiddleton** [comment]
1. Robusticity of experimental design and analysis: Data is only as good as the experimental design that produced that data. Additionally, when analyzing data one should be extremely cautious and never trust either the tools being used or the data itself. Continually checking input, output, and intermediate steps can give you much greater confidence in the results and conclusions you garner from your data.
2. Reproducibilty of the project: Clear organization and naming of directory structure are vital to quickly finding necessary parts of the data and automating the analysis. Additionally, documentation at each step in a detailed way, even if you swear that you'll remember what you did, can be vital because the simplest thing could be the reason that you can't get the same result twice.

**Comment by MeganEDuffy** [comment]
##### It's crucial to document thouroughly! Must record:
1. When and how data was downloaded, as well as origin
2. Data and software version information
3. Methods and workflow

##### Also, be hypervigilant for silent errors. Make scripts and have dummy data to check your workflows.
