### ISSUE TITLE
Project Ideas

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#12]
As I mentioned, each student will have a "project" that results in a "product". Do you have any preference to what such project is involved with? What is one idea that comes to mind based on the reading and your interests. Please include any questions or concerns.

**Comment by yaaminiv** [comment]
Because I have no data of my own, I would like to analyze someone else's data in a way that is meaningful and useful for my current project. For the project I am working on, I will need to analyze Pacific oyster proteomics data. Using data from someone else's ocean acidification experiment to develop the proteomics methods I will use, or even learning how to analyze a transcriptome, will be good practice for me. My only concern is finding the data and developing methods that could be generalized to a different experiment.

**Comment by Ellior2** [comment]
I am interested in discovering differences in the proteome between oyster seed reared at different temperatures at our shellfish hatchery. By looking into the proteome and microbiome we may be able to understand if the high mortality we see in our control group is due to pathogens, chemical imbalances, or any other potential stressors. Because our raw data are MS/MS outputs (mass to charge ratios vs relative abundances plotted on an xy graph), we will have to figure out how we can work with that in the command-line.

**Comment by nclowell** [comment]
I would like to learn how to analyze RAD data for population structure, because I know I will have to do that for at least two of my chapters. I'll poke around my lab to see if anyone has a data set I can look at, otherwise, I may need some guidance to find an interesting data set. Any RAD data set would help me develop a pipeline for my future data, but ideally I can get a hold of data for a shellfish species native to the West Coast. If I can't get a hold of any interesting RAD data, I'd like to assemble a transcriptome, as that will likely be another chapter in my dissertation.

**Comment by jldimond** [comment]
I have recently obtained [ddRAD-seq](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0037135) and [EpiRAD-seq](http://onlinelibrary.wiley.com/doi/10.1111/2041-210X.12435/abstract) data for 48 samples of _Porites_ spp. corals collected in Belize. Most of these samples consist of branching _Porites_ spp., for which there is taxonomic uncertainty whether these comprise 3 different species or a single polymorphic species. My goal is to evaluate (1) if there is any genetic structuring of these individuals using the ddRAD data and (2) if there is any epigenetic structuring of these individuals using the EpiRAD data. I will be using iPyrad to obtain the clusters of loci, and will be filtering out symbiont sequences by using the "denovo-reference" option to obtain sequences that do not match the Symbiodinium minutum genome.

At this point, the biggest unknown to me is how to approach the EpiRAD data. I know that I will need to analyze counts of fragments for each locus as a measure of methylation, and I believe this will require tools similar to what are used for RNAseq analysis.

**Comment by aspanjer** [comment]
I have the RNAseq data from 24 coho salmon liver samples collected from 4 different perennial streams. The interest is in looking for differential gene expression that would signal stress from disease and contaminants. I've taken the data through de novo transcriptome assembly, differential expression analysis, and annotation. I would like to work back through these steps to clean up the analysis and confirm the initial findings while producing a well documented analysis that is ready for publication.

**Comment by mmiddleton** [comment]
I am interested in looking at the differences in methylation between steelhead raised in a hatchery environment for their first year or two of life versus those hatched in the wild or an artificial stream environment. However, the amount of data that our lab is working with is extensive and complicated to say the least. So, after consulting with people that know what they're doing, my project will be much smaller than all of that and will involve a limited amount of data to allow me to get a handle on the software/techniques involved in doing these analyses. At this point my main concern is building a good knowledge base that I can apply to larger datasets because I have very limited experience in bioinformatics.

**Comment by mfisher5** [comment]
I am interested in learning how to analyze RAD sequencing data to look at population structure. I'm working with Pacific cod over in South Korea, and am starting to get some of that sequencing data back, so I'll have lots of RADseq data (300 samples total). I've begun running some of the data through stacks (just process_radtags so far), so I'm interested in learning more about the analysis farther down the pipeline, including de novo assembly and the variety of analyses that I can do with population structure data after it has been run through stacks. Along the lines of "do not trust your data," I'm particularly interested in understanding how changing certain parameters might change the analyses results, especially since population structure analyses seem to be pretty dependent on how the analysis programs are set up.

**Comment by laurahspencer** [comment]
I'm interested in analyzing data from hatchery shellfish (oyster, geoduck, mussel, etc.), with the goals of a) getting exposed to programs that process genetic data (DNA, RNA or protein), b) gaining a deeper knowledge of the methods used and steps required to analyze said compounds, and c) become comfortable working in the command-line, solidifying important commands and terminology.  While I am interested in working with proteins eventually, I think a good place to start is the geoduck DNA  data, as it will (hopefully) become a very useful reference for OA and other research.

**Comment by MeganEDuffy** [comment]
I want to look at a metaproteomic depth profile in the Eastern Tropical North Pacific (ETNP), where is low to zero oxygen below the surface, and microbes move on to other terminal electron receptors. Going from the oxygenated surface to the  core of the oxygen-minimum zone, I'm interested in seeing taxonomic shifts (this will likely involve using [Unipept](http://unipept.ugent.be/)) and also functional protein changes. I have run these depth samples and have MS/MS spectral data, and need to search these against databases we've made from corresponding assembled metagenomes annotated using [Prokka](http://www.vicbioinformatics.com/software.prokka.shtml)
