### ISSUE TITLE
Bash and Jupyter

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#13]
What is bash and Jupyter and what are the differences and similarities?

**Comment by Ellior2** [comment]
Bash (sometimes referred to as Unix shell or terminal) is a way for a user to interact with their computer on the command-line using scripting language. You can move large files, create directories, and get a peak at your large data sets without having to open them. Jupyter can also serve this function, but additionally you can create an online notebook that can document the scripts you use in a user-friendly format. Jupyter can also serve as wrapper and utilize a variety of different languages in one place (right now I just have Python). Instead of saving the scripts in your bash window and having to dig through them later when reproducing your work, you can save your inputs and outputs in an organized manner. Now why wouldn't you just use Jupyter all the time?

**Comment by yaaminiv** [comment]
Bash puts the user right in the command line and allows them to directly manipulate files from this interface. The main drawback to the shell is that it's difficult to save scripts in a way that intuitively makes sense. While scripts could be saved separately, reading through a bunch of command line and then trying to piece it together with other methods is cumbersome. Jupiter notebooks serve as a solution to this problem. Jupyter allows the user to write command line scripts or markdown text in the same notebook. The user can write a command that creates a new directory, and then describe these actions in a Markdown segment. This creates a more logical (and hopefully reproducible) workflow! I do have the same question Rhonda posed — why would you use Bash as opposed to working solely in Jupyter notebooks?

**Comment by nclowell** [comment]
Bash is a Unix command processor that allows you to execute commands from the command line. Jupyter is a web application that allows you to annotate and keep records of your code, in a way that makes it more human-reader-friendly. In both Bash and Jupyter, you can run code in the shell. However, only in Jupyter can you make use of added interpretive layers (rich text, GUI tools, etc.). In Bash, there is no record keeping of the code unless you write it to a file, and its limited to plain text.

**Comment by jldimond** [comment]
Bash is basically a Unix shell command language that allows you to issue commands to your computer through a command line interface like Terminal rather than a graphical interface. Jupyter is a web-based interface that allows you to create interactive notebooks with code, markdown annotations, and images for projects. You can execute code in both Bash and Jupyter, but Jupyter is ideal for projects where you want to document how you did something, and allow you or someone else to reproduce a set of commands or an entire computing project. @Ellior2, @yaaminiv, to try to address your questions above, I think there will be many instances where you want to execute some commands but there is no reason to document it in a Jupyter notebook. For example, mundane stuff like creating directories, logging into another machine remotely, or launching Jupyter notebook via the terminal.

**Comment by aspanjer** [comment]
Juypter is a web application that allows you to keep a notebook of your data analyses steps that includes executable coding (from within the web application on your machine) and has support for markdown rendering and multiple coding languages. Bash is a unix shell that allows you to execute code from the command line. Both allow you to run scripts and navigate directories on your computer but Bash does not automatically keep a history of your coding unless you output to a text file. This makes it less ideal on it's own for documenting, sharing, and reproducing your work.

**Comment by laurahspencer** [comment]
Bash, or Bourne-again shell, is a Unix program that allows you to operate among/within directories, stream data from files, and utilize data in a "read-only" fashion.  I access Bash by opening the terminal program on my Mac computer.  Jupyter is a program that combines the power of a Unix shell and the ability to write text/comments in Markdown.  To me, it represents a combination of two programs: Mou and Bash. This is powerful, as you can more easily comment and review input and output, thus it can operate as your coding notebook.

**Comment by mfisher5** [comment]
Bash is a unix shell that runs on your desktop, while Jupyter is a web applications that acts as an online notebook. Both allow you to execute code (Bash using linux, while Jupyter supports multiple programming languages), directly on the command line or through a shell script. 
However, Jupyter allows you to group related code into a single notebook, include explanatory text for your code, share notebooks with others and create visualizations; this makes it a lot easier to document what you are doing, both for yourself later on, and for others. During more complicated analyses that may require quite a bit of code, it seems best to work from Jupyter to remain organized.

**Comment by mmiddleton** [comment]
Bash is a computer based shell allowing you to interact with your computer at the command line without navigating in the more conventional way (clicking around to open files, create documents, etc.). Jupyter is a web based program that allows you to document your work through a notebook, share documents, and all kinds of other things. They are similar in that both allow you to use the command line, however Jupyter seems like more of a hybrid between the shell and a GUI, especially the notebook aspect of it which allows easy documentation of a project and code used in that project.

**Comment by MeganEDuffy** [comment]
Bash: a (Bourne-Again) Unix shell, which I still really need to unpack to understand best. A shell is a program that I can use to input commands to access my OS actions, and this can be a command line interface or a graphical user interface. Bash processes commands that I input to do things like move and sort files and directories around my computer. It can also read and execute a series of commands from a script.

Jupyter is an interactive web application that can run code in several languages (Python, R, Ruby). A Jupyter Notebook is a document that you can fill with live code, Markdown, and images.

There are a number of similarities between Bash and Jupyter, in each you're inputting and running commands. But Jupyter allows you to save both your code and output and documentation in one place, where I think of Bash as more transient in its memory and limited in its use. Jupyter notebooks can also contain rich text (paragraphs, links, equations), which is not true of Bash. I think both have their uses. As I get more familiar with using Bash, it's an efficient way to handle day to day operations (opening programs and files, checking the my git status, etc). I imagaine as we move forward, Jupyter will be really important and well-suited to documenting specific project work.
