### ISSUE TITLE
Big Week

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#49]
This week has been dedicated to your projects..
1. What was the status of your project at the beginning of the week compared to the end of the week?
2. What do you consider your biggest accomplishment this week?
3. What do you consider your biggest challenge this week?

**Comment by yaaminiv** [comment]
1. At the beginning of the week, all I had done was download my data. Now, I have run FastQC analyses on my data (both using the app and command line), and will proceed to run MultiQC analyses and BLAST.
2. My biggest accomplishment this week was learning how to do a FastQC analysis without too much guidance. I found resources I needed to complete and interpret the analysis, and was able to semi-navigate the command line process as well.
3. My biggest challenge was learning the mechanics of syncing Github Desktop with my online repo. I would make changes in the online repo and forget to pull them down to my desktop and vice-versa. Although it's not the most technical problem, fixing it did teach me better work practices. I now commit frequently and make sure my online and local repo versions do not conflict.

**Comment by mfisher5** [comment]
1. At the beginning of the week, I had visualized my raw data using FastQC, and run process_radtags to separate sequences by sample / quality filter sequences. I had also run one iteration of ustacks + cstacks to understand the basic code required. 
2. My biggest accomplishment this week was compiling information about ustacks and cstacks parameters from labmates and papers, in order to come up with the range of parameters I want to test on my own data  - [table here](https://www.evernote.com/shard/s650/sh/122752f1-9ab7-4f9b-a9af-0c3331617436/0c84d3e0f73055a695358142091fcd99)
3. My biggest challenge was becoming comfortable enough working on Jupyter and Github to switch over my analyses that are already in progress; I still have some occasional trouble working on the command line from Jupyter on my desktop computer, but am getting better!

**Comment by nclowell** [comment]
1. At the beginning of the week, I didn't have my data and I didn't even know what they would be in. By the end of the week, I had my data, saw that it is fastq, used fastqc, and had found that someone already put it through processed_radtags which removes barcodes, trims for quality, and renames files with the barcode sequence.
2. My biggest accomplishment was developing a solid 10,000 foot level understanding of the Stacks pipeline I'll be using, by reading the manual and talking to lab mates. With that, I've been more efficiently Googling my way to the right answers for what steps to do first, how to optimize parameters, etc.
3. My biggest challenge this week was falling into moments of extreme darkness with git. Pushing and pulling from the command line is easy enough, but switching between the desktop version, git hub online, and git at the command line really stretched my brain. I don't think I still understand all of the mechanics, but with some help from your students I think I've figured out how to do most of the things I imagine I'll be using it for.

---

Note if you would rather use the git command line- there is no reason you also have to use the Desktop app (I just assumed that would be easier for some) ~@sr320

**Comment by mmiddleton** [comment]
1. At the beginning of the week all I had was my data. Now that it's nearly the end of the week I have installed FastQC on both my mac desktop and my windows laptop and figured out how to use it in both interactive (windows) and non-interactive (mac) mode. I was able run my data, look at the output, and understand it for the most part. Now that I have done that I can move on to figuring out Trim_Galore to remove adapter sequences and low quality bases.
2. My biggest accomplishment for the week was getting BLAST to work on both my laptop and my desktop. Even though everyone else did that last week it was pretty difficult for me. Windows wasn't overly cooperative with BLAST until I figured out I was missing a random piece of software it required. Downloading software to the mac and editing the PATH was slightly more difficult than normal because of the restrictions about what parts of the computer the user can access on a government network.
3. My biggest accomplishment came from my biggest challenge since the BLAST installation was so difficult to figure out. The fact that it was such a challenge was pretty great though since I tried just about everything to make it work (re-install, edit the PATH, etc., etc.). Doing it mostly on my own helped me get a better understanding of downloading bioinformatics software, operating programs from the command line, and editing the PATH.

**Comment by jldimond** [comment]
1. At the beginning of the week I had just finished one round of ipyrad analysis and had a better idea of how to proceed with something better. That analysis is now running.
2. Learning how to deal with VCF files and extracting read counts. 
3. Learning how to deal with VCF files and extracting read counts. :stuck_out_tongue:

**Comment by aspanjer** [comment]
1. At the beginning of the week had collected the raw reads from each of my individually sequenced files and had an organized directory structure. By the end of this week I've been able to set up jupyter notebook to work with my computer, been able to run all 48 files through the fastqc check, collect all that data together with MultiQC, and perform trimming with trim galore to prepare my data for trinity assembly. 
2.  My biggest accomplishment was finally understanding how bash works with packages, that is how to use anaconda to manage installed python packages, how to resolve conflicts with the same packages being installed in different directories, how to use other packages and scripts that can't be installed with anaconda and how to get this all working with jupyter. This will undoubtedly speed up my analysis in the future. 
3. My biggest challenge was resolving conflicts that resulted from poor package installation management on my computer from when I've attempted all this in the past. For example, I had two versions of anaconda installed and the script for 'cutadapt' installed in three places, thus creating conflicts that wouldn't allow it to run. Getting on top of this organization has been a challenge.

**Comment by Ellior2** [comment]
1) At the beginning of the week, I had my data and was still unsure what I should be doing with it. I figured out how to do a Blastp (and that it was even appropriate for my dataset) and became more comfortable with using relative paths. I started thinking about how to write the commands in my Jupyter notebook to work on another computer by using relative paths. 

2) My biggest accomplishment this week was getting organized. I learned how to create folders in my repo and move files around. This will be essential as I progress further with my projects in this class.

3) My biggest challenge is getting my local GitHub and cloud GitHub to communicate properly. Sometimes it works, sometimes it doesn't. I get errors that it failed to sync and I need to open a shell and debug the state of the repo. I have overcome this issue a couple times by deleting the local repo and recloning the cloud repo to my local GitHub desktop but there must be something I'm missing.

**Comment by laurahspencer** [comment]
1. As of Sunday I had obtained the geoduck genome data file via `curl`, checked it out via `head`, and had learned the basics of `blast`.  As of today I have subsetted the genome file to select scaffolds larger than 70k bp, downloaded the gonad transcriptome file, and blasted it against the 70k genome file. If blasted correctly, there are 3,366 matches.  
2. My biggest accomplishment was troubleshooting issues/deciphering error messages. E.g. I determined that I had a corrupted .zip file; I had trouble synching GitHub desktop to the cloud due to large files that were committed (had to revert commit, add file name to .gitignore, recommit); I realized that a script I was trying to use was written in perl, which is a diff't language (next step-figure out how to translate perl to bash, or how to use perl).
3. Biggest challenges are: understanding scripts that other people have written, and how I need to customize them for my use; figuring out ways that I can QA/QC my data analyses, aka have actually worked the way I want them to work?
