### ISSUE TITLE
Clarification on HW

### ISSUE THREAD

**Issue by Ellior2** [sr320/course-fish546-2016#60]
To find a gene in our target organism that is also differentially expressed in a sea star with wasting disease, are we running blastx using a seastar transcriptome as a database and our query as our target organism? I found a contigs fasta file for a seastar that has had sea star wasting syndrome (_Patiria miniata_) on [Echinobase](http://www.echinobase.org/Echinobase/) and I found a _C.gigas_ transcriptome fasta file on [figshare](https://figshare.com/articles/Crassostrea_gigas_male_gonad_transcriptional_data_comparison/1004464)

I tried blastx, but I keep ending up with a blank text file. Can you provide a little more direction or clarification?

**Comment by sr320** [comment]
Great question! 
Couple things 
1) provide a url to what you are doing to better troubleshoot
2) comparing two nucleotides sequences is blastn 

---

Also you would only want to use the sea star seqs that are differentially expressed. Determined by using DESeq2 in R. Then use those seqs to compare to gigas (just use the proteome you are working with) That would be blastx

**Comment by mmiddleton** [comment]
I am having a hard time with that part as well...
I got through the R part okay and ended up with the Phel_DEGlist.tab file, but now I'm confused about how to blast that since there aren't any sequences in that file, just the contig names (unless I understand less than I thought that I did, which is highly probable). Should we be getting a different file out of the repo and blasting that?

**Comment by yaaminiv** [comment]
I have a similar question to @mmiddleton !

I tried using the Phel_DEGlist.tab file as a database, but got the following error:
![screen shot 2016-10-26 at 11 05 48 pm](https://cloud.githubusercontent.com/assets/22335838/19756364/cd415952-9bd0-11e6-97eb-e11613743567.png)

Is there a different FASTA file we should be using as a database instead?

And another question:
I'm comparing .fastq files to the seastar genes. Does this mean I'm doing a blastn?

**Comment by laurahspencer** [comment]
I third this question; I had previously assumed that the next step was to use R to merge the Phel_DEGlist.tab file with our file (in my case I use the geoduck transcriptome file). However, since there are only contig names, which I don't believe have a standard naming convention based on bp sequence, i'm unsure how to move forward.  Unless ... 
... Do we retrace our steps using the contig names to determine the contig sequences (from original fasta file), then blast subsetted sea star fasta against our fasta? If so, I would guess that we can do this in R.

**Comment by sr320** [comment]
Think about it this way- what do you need to move forward?

**Comment by sr320** [comment]
You are doing it exactly correct..

How would one take that list and get sequence info? Hint: look at the files
in the eimd-sswd repo. What would you need to do?
