### ISSUE TITLE
miRNAs

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#77]
What are miRNAs? 
What are two methods to identify miRNAs in sequence data?

**Comment by yaaminiv** [comment]
miRNAs are use for gene silencing. They prevent mRNA translation by binding to the mRNA and inhibiting translation, or by cutting the mRNA.

miRBASE is a searchable database with published miRNA sequences and annotation that can be used to find miRNA sequences. PITA allows the user to input a UTR sequence and find miRNAs in that sequence using a query miRNA sequence. Sfold is a suite of analytical tools, including STarMir, which predicts miRNA binding sites.

**Comment by Ellior2** [comment]
miRNAs (microRNAs) are small non-coding RNA molecules usually about 19-25 nucleotides in length and serve in the process of gene silencing. When they bind to target sites within the 3' UTR of the targeted mRNA, it prevents protein production and synthesis and/or initiates the degradation of mRNA. miRNAs can play major roles in biological development and processes. Recent studies have linked the dysregulation of miRNAs to the progression of diseases in both animals and humans.

[Tools4mirRs](https://tools4mirs.org/software/mirna_databases/) is a platform where you can search for relevant databases concerning miRNAs and select features specific to your organism or research interests.

[PITA](https://genie.weizmann.ac.il/pubs/mir07/mir07_prediction.html#) has an miRNA prediction tool where you can enter a fasta sequence of a UTR and it will search for potential miRNA targets based on supplied seed matching tools.

**Comment by nclowell** [comment]
miRNAs are small non-coding RNAs that regulate biological processes by binding to target sites on mRNA and interfering with gene expression.

Two methods for identifying miRNAs in sequence data include (1) mirEval and (2) miRDeep2.

(1) mirEval is a web tool that uses four criteria to identify miRNAs: secondary structure analysis, conservation analysis, cluster analysis, and miRBase Blast.

(2) miRDeep2 is a module that identifies known miRNAs given miRBase files and novel miRNAs using a search algorithm. It also maps miRNAs to the genome and sums read counts for miRNAs.

**Comment by laurahspencer** [comment]
Micro RNA (miRNA) are small, non-coding regions that act as the "switch" to turn genes off and on;  they are an energy-efficient method of regulating gene expression. Tools for identifying miRNA sequence data include: 

1) The online tool available at www.mirbase.org; if you don't have a known miRNA sequence, you can use this program to find locations on your transcriptome/DNA where it's likely that you have miRNA.
2) The site www.tools4mirs.org is a database of many available software/tools for known miRNA sequences, searchable based on organism, known genome, etc.

**Comment by mfisher5** [comment]
miRNA are very small, non-coding RNAs that bind to mRNAs in order to prevent translation, accomplished by either cutting the mRNA or interfering with ribosomes. This silences targeted genes. 

Methods for identifying miRNAs in sequence data: 

(1) [miRDeep2](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3245920/) software package consists of three modules that can be run on the command line. It uses an improved algorithm to output a single .html file for each analysis, which contains links to all results generated by the module. There are a variety of applications that use the miRDeep2/miRDeep algorithm as a base, including miRDeep2-P specifically for plants, and miRDeep*, which has a more user friendly GUI. 
(2) [PITA](https://genie.weizmann.ac.il/pubs/mir07/index.html) is an miRNA target prediction tool that is an online searchable database as well as a downloaded executable. It contains predicted miRNA targets in worm, fly, mouse and human. You can specify certain seed parameter settings and input a sequence into the database; PITA can identify and score microRNA targets on UTRs.

**Comment by aspanjer** [comment]
microRNA (miRNA) are small non-coding RNAS (~20 bp in length) that are involved in regulating gene expression through gene silencing. They work by complexing with a protein and binding to target messenger RNAs, thus preventing translation and causing mRNA breakdown through deadenylation. 

miRDeep2 is a software package developed for the identification of miRNAs in sequencing data using the miRBase database of known miRNA sequences.  

another option is...

miRNAkey, which provides a GUI interfaced analysis pipeline for identifying miRNAs in samples and conducting differential expression analysis on count results.

**Comment by jldimond** [comment]
miRNAs are short non-coding RNAs that act as gene silencers by either cutting or interfering with mRNA post-transcription.

Options for identifying miRNAs include the following databases:

http://www.mirbase.org/

http://www.mirdb.org/miRDB/

**Comment by mmiddleton** [comment]
miRNAs, which stands for micro RNAs, are short, non-coding RNAs which are highly associated with gene silencing. As part of the RISC (RNA induced silencing complex), which consists of a single strand of the miRNA (guide strand) and proteins (including AGO2), the miRNA binds to mRNA (messenger RNA). While bound, the RISC can silence genes in one of two ways: proteins either cut the mRNA or the presence of the complex inhibits translation because it doesn't allow the binding of ribosomes.

Some tools to identify miRNAs are:
Tools4miRs which can be used either locally on your machine or online where you can filter for different species, research interests, sequencing platforms, and all kinds of other things. (The video on the home page is also pretty cool).

STarMir is also pretty cool if you have already identified miRNAs in your sequence data. You can put in the sequences of your miRNA along with a sequence of mRNA and it can tell you where the miRNA would bind along that mRNA sequence.

**Comment by MeganEDuffy** [comment]
Micro RNAs (miRNAs) are short, non-coding RNA molecules that regulate gene expression. By base-pairing with complementary sequences of mRNAs, miRNAs silence gene expression in an energy-efficient manner.  Also, they can cause some [cancers](http://www.nature.com/nature/journal/v518/n7537/full/nature13905.html).

_How are miRNAs identified in sequencing data?_

[PITA](https://genie.weizmann.ac.il/pubs/mir07/mir07_data.html) has a series of catalogs of predicted microRNA targets. Files you can download there contain lists of predicted microRNA targets in worm, fly, mouse, and human. You can also use an miRNA prediction tool, supplying a UTR sequence so PITA can search for potential miRNA targets based on supplied seed matching tools (size, conversation minima).

[miRBase](http://www.mirbase.org/) also provides searchable and downloadable databases of published miRNA sequences and annotations. Additionally it provides a gene naming and nomenclature tool in the miRBase Registry. Since we're focusing on releases this week, I was drawn to miRBase's [notification](ftp://mirbase.org/pub/mirbase/CURRENT/README) of their [latest release](ftp://mirbase.org/pub/mirbase/CURRENT/README) on the site.
