### ISSUE TITLE
Post release improvements

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#82]
Last week you took to bold move to make your first `release`. For this week project-progress simply provide a bulleted explanation of all the improvements to your project since the `release`.

**Comment by mfisher5** [comment]
**Project Goals for this Week:**
(1) Repeat Week 5 comparisons made with ustacks -m parameter for the ustacks -M and cstacks # individs in catalog

(2) Determine which quantitative measurements should matter the most when comparing parameter outputs.

**Progress**
(1) repeated Week 5 comparisons with the ustacks -M parameter (# of loci retained AND graphing heterozygosity with R code) as well as the cstacks # individs for catalog (# of loci retianed ONLY)
- [Jupyter notebook](https://github.com/mfisher5/mf-fish546-2016/blob/master/notebooks/Testing%20stacks%20Parameters%20II.ipynb) for step-by-step guide and code
- [Evernote notebook](https://www.evernote.com/shard/s650/sh/138af148-ea28-416e-b79d-2550b2829d50/3dd0a2619d17e859) for graphical comparison

(2) Decided that I will _most likely_ use a stack depth (-m) of 5 and and -M of 3. Have not thoroughly looked over the cstacks' parameter, # individs for catalog. 

(3) Decided that I might also explore the upper / lower bound error rate parameters in ustacks (`--bound_low and --bound_high`)

(4) Tackling the question of whether the stacks program `populations` undercalls heterozygotes by running independent scripts on the output. So far have run into a lot of trouble here, as these scripts were written for a different version of stacks.
- Jupyter notebooks [I](https://github.com/mfisher5/mf-fish546-2016/blob/master/notebooks/Stacks%20-%20Undercalling%20Heterozygotes.ipynb) and [II](https://github.com/mfisher5/mf-fish546-2016/blob/master/notebooks/stacks%20-%20Undercalling%20Heterozygotes%20II.ipynb)

**Comment by yaaminiv** [comment]
This week, I was mainly troubleshooting all of the problems I ran into last week.
- Successfully got my blastx to run (and it's still running :sweat_smile: )
- Got `kallisto quant` to work with my data
- Setting up DeSeq2 analysis for next week

**Comment by Ellior2** [comment]
Progress from this week:

1) Double checked to make sure my blast output was complete by checking to see if the tail end of output file contained contigs from my query. Here is my [notebook](http://localhost:8888/notebooks/Documents/GitHub/Fish-546-Bioinformatics/notebooks/gigas_prot/002-MergeUniprot.ipynb)

2) Turned my geoduck blast output that I merged with a Uniprot database into a large [table](https://github.com/Ellior2/Fish-546-Bioinformatics/blob/master/analyses/gigas_prot/Cgig_Pgen_table.xlsx)

3) I also created a [table](https://github.com/Ellior2/Fish-546-Bioinformatics/blob/master/analyses/taylor/Uniprot_merge.xlsx) with the proteins found in the Taylor oyster seed experiments after merging with the uniprot database.

**Comment by nclowell** [comment]
I figured out how to run sstacks, the penultimate program in the Stacks pipeline, and wrote a python script so that I can rerun it from the command line simply. The script writes and runs a shell script to accomplish this. Here's the [markdown file](https://github.com/nclowell/FISH546/blob/master/Cod-Time-Series-Project/Scripts/Markdown_files_for_scripts/pypipe_sstacks.md). 

In addition, I've made some progress on figuring out how to call filepaths so that I can streamline use no matter the directory structure. I've also made progress on sorting out what additional analyses and filtering my lab group does with RAD data to do after running populations, the final program in the Stacks pipeline.

**Comment by aspanjer** [comment]
For week 6:
- My full transcriptome assembly finally ran in Galaxy, resulting in 350k contigs (up from the 170k contigs in the smaller assembly)
- Using transrate, I ran an analysis on this new assembly 
- I used this new transcriptome to rerun the previously established analyses (Kallisto and DESeq2)
- Additionally I blasted the new transcriptome against a database of salmon proteins and against the swissprot database (the later being used for GO enrichment analysis)
- I began using DAVID for GO enrichment, but realized that the salmon Uniprot IDs aren't in the DAVID database, so had to go back and blast against the Uniprot reviewed database
- I also worked on visualizing results, exploring the use of heat maps in different BioConductor packages, which I hope to have something usable from shortly.

**Comment by mmiddleton** [comment]
I spent this week trying to get to a point where I could run my Bismark analysis. I was able to:
- Get the software and all it's dependencies downloaded and working
- Read through the Bismark user manual (which is pretty extensive)
- Start the bisulfite conversion of my genome (this step was started yesterday and will likely run through the weekend, so I am considering different options for running the mapping step like using CoGe or using a computer with more RAM/better processor than mine)

This week's accomplishments and goals for next week have been updated on my [README](https://github.com/mmiddleton/mmiddleton-fish546)

**Comment by laurahspencer** [comment]
Since my v01 "pre-release" I have done the following:  

**Progress Made**
1. Learned how to use the command line to communicate with Git, since GitHub Desktop was severely malfunctioning. I now commit/push/pull using the command line!  
2. Located the appropriate Uniprot-annotated geoduck transcriptome, used Galaxy to merge it with my data file to create [one large and data-rich file](https://github.com/laurahspencer/546-Bioinformatics/blob/master/2016-10_Geo-Ann-Project/data/Geo-70k-scaff-annotations-merged-table.tabular).  
3. Researched & sketched out the meaning of each column in the blast results file, Uniprot-transcriptome file, and the GFF format. Struggled trying to convert my large data file to a format (GFF or BED) that is viewable on the IGV tool, but after chatting w/ Steven I will now leave that effort until later.  
4. Got a  better handle on the end-goal/product  
5. Prepped for transposable element analysis: registered for and downloaded the the RepeatMasker app and the required dependencies (I think I got them all). Will use [Sean's blogpost](https://seanb80.github.io/blog/2016/11/04/Installing-RepeatMasker) as a guide.  
6. Was thoroughly distracted and mortified by the election results (not progress, but still had to mention it...)  

**Next Steps**  
1. ID the transposable elements using RepeatMasker  
2. Use CoGe to ID the CpG loci for potential methylation frequency/locations  
3. Use online tools such as [PITA](https://genie.weizmann.ac.il/pubs/mir07/mir07_prediction.html) or [mirbase](http://www.mirbase.org/) to try to ID likely miRNA sequences in the transcriptome sequences found on the >70k genome scaffolds  
4. Identify the tool to use to ID lncRNA in my data

**Comment by jldimond** [comment]
- I made a branch called `Macbook_local` for work done on a repository on my personal laptop.
- I played around with some analyses in R. 
- Played with DESeq2 for the EpiRAD analysis and decided it is not appropropriate for this data.
- I keep coming back to using residuals for the EpiRAD analysis. 
- I also played with the `prcomp` function for principal components analysis.

**Comment by MeganEDuffy** [comment]
Progress post release:
- Finally got `Homebrew` and installed `gdrive` so I can now interact with my Google Drive directories to access files there. 
- Created a notebook for documenting protein database searching using Water's ProteinLynx Global Server (PLGS) and used a previously downloaded marine sediment metagenome to identify proteins in my samples (they were all hypothetical...) 
- Searched around quite a bit on [iMicrobe](http://data.imicrobe.us/project/view/26) Global Ocean Sampling Project to find new data that I can use to build a better database to search against.  
- Starting using `blastp` to identify _de novo_ sequenced peptides.
